django/20220929/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls')),
    # 프로젝트 전체의 urls 파일에서 todos의 urls을 include 해야함
    # todos에 있는 urls 파일을 가지고 오라는 의미(include)
    # 이렇게 하면 앱의 urls가 분리가 된 것임
    # path('')에서 ''에 들어가는 것이 url 주소 입력했을때
    # localhost:8000/ 다음에 들어감
]

django/20220929/crud/todos/urls.py
from django.urls import path
# path 추가
# 모듈 이름 기억 안나는 경우 
# 프로젝트의 urls가서 복사한 후 include만 지워주면 됨

from . import views
# views 추가

# url namespace
# url을 이름으로 분류하는 기능

app_name = "todos"
# include를 사용하는 것은 공간적인 분리
# 한 파일에 있어야 하는 것을 나눔으로써 코드의 공간을 나눔
# app_name을 지정하는 것은 만약 index를 다른 곳에서 사용하고 싶어도 사용할 수 없기 때문
# 동일한 이름은 장고 프로젝트 내에서 1개만 쓸 수 있다

urlpatterns = [
    path('', views.index, name='index'),
    # path를 추가하는데 url은 ''이고, views 함수는 index 함수로 향하게 됨
    # ''주소로 요청하면 views에 있는 index를 함수로 응답한다는 의미
    # ''urls 대신 이름을 지정하는데 변수이름 지정하듯이 name을 index로 지정한다는 뜻

    path('create/', views.create, name='create'),
    # 이름을 create로 만들고 create/로 요청할거라는 뜻
    # views는 create라는 함수를 요청한다는 의미

    path('delete/<int:todo_pk>', views.delete, name= 'delete'),
    # 이름 delete, 주소 delete/<todo_pk>, 여기서 <todo_pk>는 동적인자
    # int타입 지정안해도 되긴함
]

django/20220929/crud/todos/models.py
from django.db import models

# Create your models here.
# django에서 DB에서 data는 models를 의미함
# 템플릿: 화면
# 뷰: 데이터 가공하여 템플릿으로 전달, 요청과 응답을 처리
# 모델: 데이터베이스의 데이터

class Todo(models.Model):
    # django에서 pk(id)는 자동으로 만들어줌
    # models에 Model을 상속받아야함

    content = models.CharField(max_length = 80)
    # models에 CharField 필드, 최대 80자까지 작성가능

    completed = models.BooleanField(default=False)
    # default는 데이터를 생성할 때 값을 넣지 않으면 자동으로 값을 채워서 데이터를 생성해줌
    # 메모앱을 기준으로 메모를 할때 미완료인 상태로 메모를 만들기 때문에 default값을 거짓으로 생성함
    




    # 데이터 추가하면 다시 마이그레이트 해줘야 함

django/20220929/crud/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
# models의 Todo 함수를 import함
# redirect는 입력했을시 create에서 안보기 때문에 사용
# redirect하면 todos:index를 요청했기 때문에 root로 돌아옴(index가 현재 root페이지임)
# root 페이지에서 입력하면 다시 root 페이지로 돌아온다는 의미

def index(request):
    _todos = Todo.objects.all()
    # 만들어 놓은 데이터를 불러오는 ORM 코드
    # 불러온 데이터를 todos라는 변수에 할당
    context = {
        "todos" : _todos,
    }
    # templates 변수에서 _todos를 출력해야 하기 때문에 context라는 딕셔너리 변수 만들고 _todos를 넘겨줌
    # 만든 context를 render 함수의 인자로 넘겨줌 return render(request, 'todos/index.html',context)
    return render(request, 'todos/index.html', context)
    # index 페이지를 만든다
    # todos/index.html: 이건 앱 안의 templates안의 todos 안의 index.html

def create(request):
    content = request.GET.get("content_")
    # templates에서 데이터를 get해야됨
    # input name에 있는 content_로 데이터를 받아옴
    # request.GET.get를 이용해서 값을 가져옴
    
    Todo.objects.create(content=content)
    # DB에 저장
    # Todo에 objects에 create메소드 사용
    # create메소드 안에 content 필드를 넣음

    return redirect('todos:index')
    # 원래 return render(request, 'todos/index.html') 지만 render 대신 redirect사용
    # redirect하면 todos:index를 요청했기 때문에 root로 돌아옴(index가 현재 root페이지임)


def delete(request, todo_pk):
    # todo_pk라는 인자를 받음
    todo = Todo.objects.get(pk = todo_pk)
    # 삭제 해야될 값을 불러와야하고 삭제할 값을 todo에 저장함
    # 불러오는 방법은 Todo.objects.get(pk = todo_pk)
    todo.delete()
    # todo save를 여기서 하게되면 안됨: save를 하게되면 동일한 데이터가 또 생성됨
    return redirect('todos:index')
    # return을 root페이지로 redirect함

django/20220929/crud/todos/templates/todos/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <h1>index.html</h1>

  <!-- 사용자에게 정보를 입력받을 때 -->
  <!-- form 태그를 사용해야 한다.-->
  <form action="{% url 'todos:create' %}">
    <!-- action: 어떤 url을 요청할지 -->
    <!-- create라는 주소를 요청할건데 url naming을 사용함-->
    <!-- url naming은 for과 if문처럼 \{% %\}를 사용하고 -->
    <!-- \{% url '' %\} url ''를 넣어서 url ''를 찾아달라고 하는 것 -->
    <!-- 여기선 create라는 이름을 가진 주소를 요청해달라는 의미 -->
    <!-- 만들어 줬으면 urls.py에서 path를 만들어줘야함 -->
    <!-- 근데 urls.py에서 app_name을 todos라고 지정했기 때문에 todos:create라고 해야함-->
    <!-- form에서 create함수로 데이터를 넘겨줘야 함 -->
    <!-- 그래서 input name에 이름을 content_로 지정해주고 -->
    <!-- views 함수에 content_로 데이터가 전송됨 -->
    <!-- 주의할 점: url 띄우고 url naming('todos:create') 적기 -->
    <input type="text" name="content_" maxlength="10">
    <!-- input:text하고 탭 누르면 <input type="text" name="" id=""> 나옴-->
    <!-- maxlength는 프론트에서 글자가 10개까지만 쓸 수 있게 하는 것 -->
    <!-- 프론트 엔드에서도 유효성 검사가 가능하므로 프론트와 백 둘다 검사 해야함-->
    <!-- 백에서는 models.py에 max_length = 80가 같은 기능을 함 -->
    <input type="submit" value="할 일 추가">
  </form>

  <hr>

  <ul></ul>

  <!-- DTL for문 사용법 -->
  {% for todo in todos %}
  <li>{{ todo.pk }} - {{ todo.content}} - {{ todo.completed}}
    <!-- todo에 id와 content를 출력하려면 todo.id나 todo.content -->
    <a href="{% url 'todos:delete' todo.pk%}">삭제</a>
    <!-- delete 할때 todo의 pk(id)가 필요함 -->
    <!-- pk 전달방법은 띄워써서 todo.pk -->
    <!-- 그럼 동적인자(url을 변수사용하듯이 사용하는 기능)로 전달됨 -->
  </li>
  {% endfor %}
  <!-- endfor를 사용해서 닫아줌 -->
</body>

</html>